# -*- coding: utf-8 -*-
"""Day27 f strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ChILEPK7ILPoOeDl3lKxt4yaVrld6qEP

f-strings or formatted strings literals, were introduces in python 3.6 as a concise and convenient way to embed expressions inside  strings literals . here are examples of using f-strings in python
"""

name="Alice"
age=30
print(f"My name is {name} and I am {age} years old")

"""Arithemetic Expressions:"""

x=5
 y=10
 print(f"the sum of {x} and {y} is {x+y}")

"""Floating Formating:"""

pi=3.1415926
print(f"Value of pi: {pi:.2f}")

"""Data Formating:"""

from datetime import datetime
today=datetime.today()
print(f"Today is {today:%Y-%m-%d}")

"""Boolean Expression:"""

is_sunny = True
print(f"Is it sunny today? {'Yes' if is_sunny else 'No'}")

"""String Methods:"""

message="hello"
print(f"Uppercase:{message.upper()},length:{len(message)}")

"""Dictionary Values:"""

person = {'name': 'Bob', 'age': 25}
print(f"Person: {person['name']}, Age: {person['age']}")

"""List Comprehension:"""

numbers=[1,2,3,4,5,6]
print(f"Sum of squares: {sum(x**2  for x in numbers)}")

"""Formatte Intergres"""

numbers=[1,2,3,4,5]
print(f"Sum of squares: {sum(x**2 for x in numbers)}")

"""Inline If-Else:"""

x=7
print(f"The number is {'even' if x % 2 == 0 else 'odd'}.")

"""Using ! for strings Representation:"""

class MyClass:
  def  __str__(self):
    return "Custom String Representaion"
obj = MyClass()
print(f"object: {obj!s}")

"""Calling functions:"""

def greet(name):
  return f"Hello,{name}!"
print(greet("Johan"))

"""HExadecimal Representation:"""

numbers=225
print(f"HExadecimal:{message}")

"""Using Expressions:"""

a,b=5,10
print(f"The avrage of {a} and {b} is{(a+b)/2}")

# Multiline strings:
name ="Alice"
age=30
message=(
    f"Name:{name}\n"
    f"Age:{age}"

)
print(message)

Percentage=75.5
print(f"Percentage: {Percentage:.1%}")

path = r"C:\Users\John\Documents"
print(f"Path: {path}")

x = 10
print(f"The double of {x} is {x*2}")

