# -*- coding: utf-8 -*-
"""Day30 Recursion in python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VrI9YMNVC8htSh1Xkzbqo4n2LSNoOcfE

Recursion in python   


Recursion is the process of defining something in terms of itself.

Ptyhon Recursive Function

In python, we know that a function can call other functions It is even  possible for the fucntion to call  itself . These types of construct are termed as recursive function
"""

# Example1
def factorial(num):
    if (num == 1 or num == 0):
        return 1
    else:
        return (num * factorial(num - 1))
factorial(5)

def factorail(n):
  if(n==1 or n==0):
    return 1
  else:
    return (n*factorail(n-1))
factorail(3)

def fibonacci(n):
    """Return the nth Fibonacci number using recursion."""
    if n <= 0:
        return "Invalid input, please provide a positive integer."
    elif n == 1:
        return 0
    elif n == 2:
        return 1
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)

fibonacci(5)

fibonacci(6)

"""In this example, the fibonacci function is defined recursively. The base cases are when n is 1 or 2, in which case the function returns 0 or 1, respectively. For values of n greater than 2, the function returns the sum of the (n-1)th and (n-2)th Fibonacci numbers."""

