# -*- coding: utf-8 -*-
"""Day33 Dict in python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15GeAAT4MjAwfrcUknCoaBpsLC4wEN4Pz

In Python , a dictionary is a collection of key -value pairs, where each key must be unique . It is denoted by curly braces"{}" and is a mutable, unordered collection,

Ways of creating the dictionary
"""

# Empty Dictionary
my_dict={}
print(my_dict)

# Literal Notation:
my_dict={"key": "value1","kye":"value2"}
print(my_dict)

# Dict() constructor:
my_dict=dict(key1="value1",key2="value2")

print(my_dict)

# using zip function:
keys=["key1","key2","key3"]
values=["value1","value2","value3"]
my_dict=dict(zip(keys,values))

print(my_dict)

# using a loop:
keys=["key1",'key2']
values=["value1","value2"]
my_dict={}
for key,value in zip(keys, values):
  my_dict[key]=value

print(my_dict)

# dict.fromkeys() Method:
keys = ['key1', 'key2']
default_value = 'default'
my_dict = dict.fromkeys(keys, default_value)

# Dictionary comprehension:
keys=["key1","key2"]
values=['value1',"value2"]
my_dict={key:value for  key ,value in zip (keys,values)}

# mergiong dictionaries (Python 3.9 and later)
dict1={"key":"value1"}
dict2={"key":"value2"}
my_dict={** dict1,**dict2}

print(my_dict)

