# -*- coding: utf-8 -*-
"""Day34 Dict methods.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L2UApyvK3-hJRH43hfv46fF2r1DL7SwR
"""

# clear(). method
my_dict={"key1":"value1","key2":"value","key3":"value3"}
my_dict.clear()
print(my_dict)

# copy() method
ornagil_dict={"key":"value1","key2":"value2"}
copied_dict=ornagil_dict.copy()

print(copied_dict)

# get(key,default),method:
my_dict = {'key1': 'value1', 'key2': 'value2'}
value = my_dict.get('key3', 'default_value')

# items() method:
my_dict={"key1":"valye1","key2":"value2"}
items=my_dict.items()

print(items)

# keys()method:
my_dict={"key1":"value1","key2":"value2","key3":"value3"}
keys=my_dict.keys()

print(keys)

# values() methods:
my_dict={"key1":"value1","key2":"value2","key3":"value3"}
print(my_dict.values())

# pop(key,default) Methods:
my_dict={"key1":"value1","key2":"value2"}
value=my_dict.pop("key1")

print(my_dict.values())

# popitem() Method:
my_dict={"key":"value1","key2":"value2"}
item=my_dict.popitem()

print(my_dict)

# update() method:
dict1={"key1":"value1","key2":"value2"}
dict2={"key2":"value2","key3":"value3"}
dict1.update(dict2)

# setdefault(key,default) Method:
my_dict={"key":"value","key2":"value2"}
value=my_dict.setdefault("key3","default_value")

# fromkeys(iteralbe,default),Method:
# Create  a new dicionary with keys the iterable and vales set to the default value(or None id not specified)
keys = ['key1', 'key2', 'key3']
default_value = 'default'
my_dict = dict.fromkeys(keys, default_value)

