# -*- coding: utf-8 -*-
"""day 55 snake water  python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pr39jhkCffNF_sA7K8-B8X99fEQNTE-A
"""

import random

def get_user_choice():
    user_choice = input("Enter your choice (snake, water, or gun): ").lower()
    while user_choice not in ["snake", "water", "gun"]:
        print("Invalid choice. Please enter snake, water, or gun.")
        user_choice = input("Enter your choice (snake, water, or gun): ").lower()
    return user_choice

def get_computer_choice():
    return random.choice(["snake", "water", "gun"])

def determine_winner(user_choice, computer_choice):
    if user_choice == computer_choice:
        return "It's a tie!"
    elif (
        (user_choice == "snake" and computer_choice == "water") or
        (user_choice == "water" and computer_choice == "gun") or
        (user_choice == "gun" and computer_choice == "snake")
    ):
        return "You win!"
    else:
        return "Computer wins!"

def play_game():
    print("Welcome to Snake-Water-Gun Game!")
    while True:
        user_choice = get_user_choice()
        computer_choice = get_computer_choice()

        print(f"\nYour choice: {user_choice}")
        print(f"Computer's choice: {computer_choice}")

        result = determine_winner(user_choice, computer_choice)
        print(result)

        play_again = input("Do you want to play again? (yes/no): ").lower()
        if play_again != "yes":
            print("Thanks for playing! Goodbye!")
            break

if __name__ == "__main__":
    play_game()

"""This simple program allows the user to play the Snake-Water-Gun game against the computer. The user is prompted to enter their choice, and the computer randomly selects its choice. The winner is determined based on the game rules, and the user can choose to play again or exit the game."""

